import { scrypt, timingSafeEqual } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { createServer } from 'node:http'
import { promisify } from 'node:util'

// Only file this process is allowed to write. Root watches for it
// in reboot-request.path and reboots the server.
const REQUEST = '/run/reboot-button/request'
const PASSWORD = '/etc/reboot-button.passwd'
const ORIGIN = 'https://susedko-reboot.local'
const PORT = 8015

const PAGE = readFileSync(new URL('index.html', import.meta.url))

// We keep only scrypt hash of the password, generated by builder
let [USER, , salt, key] = readFileSync(PASSWORD, 'utf8').trim().split(':')
const SALT = Buffer.from(salt, 'base64')
const KEY = Buffer.from(key, 'base64')

const scryptAsync = promisify(scrypt)

async function isAuthorized(header = '') {
  let [scheme, encoded = ''] = header.split(' ')
  if (scheme !== 'Basic') return false
  let credentials = Buffer.from(encoded, 'base64').toString()
  let separator = credentials.indexOf(':')
  if (separator === -1) return false
  let user = credentials.slice(0, separator)
  let password = credentials.slice(separator + 1)
  let hash = await scryptAsync(password, SALT, KEY.length)
  return timingSafeEqual(hash, KEY) && user === USER
}

createServer(async (req, res) => {
  // Check password here and not in nginx to protect from local processes,
  // which can connect to our port directly
  if (!(await isAuthorized(req.headers.authorization))) {
    res.writeHead(401, {
      'WWW-Authenticate': 'Basic realm="Susedko", charset="UTF-8"'
    })
    res.end()
  } else if (req.method === 'GET' && req.url === '/') {
    res.writeHead(200, {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store',
      'Content-Security-Policy':
        "default-src 'none'; script-src 'unsafe-inline'; " +
        "style-src 'unsafe-inline'; connect-src 'self'; " +
        "base-uri 'none'; form-action 'none'; frame-ancestors 'none'"
    })
    res.end(PAGE)
  } else if (req.method === 'POST' && req.url === '/reboot') {
    // Protect from CSRF: other websites can't send POST with our Origin
    if (req.headers.origin !== ORIGIN) {
      res.writeHead(403).end()
      return
    }
    try {
      writeFileSync(REQUEST, '')
      process.stdout.write('Reboot requested\n')
      res.writeHead(202).end()
    } catch (e) {
      process.stderr.write(`${e.stack}\n`)
      res.writeHead(500).end()
    }
  } else {
    res.writeHead(404).end()
  }
}).listen(PORT)
