# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation andrey: !include automations/andrey.yaml
automation blind: !include automations/blinds.yaml
automation climate: !include automations/climate.yaml
automation leaving: !include automations/leaving.yaml
automation lights: !include automations/lights.yaml
automation notifications: !include automations/notifications.yaml
automation tv: !include automations/tv.yaml
automation water: !include automations/water.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
