blueprint:
  name: Свет по датчику присутствия
  description: Включает свет когда кто-то находится в комнате
  domain: automation
  input:
    presence_sensor:
      name: Датчик присутствия
      selector:
        entity:
          filter:
            - device_class: occupancy
              domain: binary_sensor
            - device_class: motion
              domain: binary_sensor
            - device_class: presence
              domain: binary_sensor
    light:
      name: Лампа
      selector:
        target:
          entity:
            domain: light
    extra_off:
      name: Дополнительное действие при включении
      selector:
        action: {}
      default: []
    night_scene:
      name: Ночной режим
      selector:
        entity:
          domain: scene

mode: restart

triggers:
  - platform: state
    entity_id: !input presence_sensor
    from: "off"
    to: "on"

conditions:
  - condition: state
    entity_id: input_boolean.stop
    state: "off"
  - condition: state
    entity_id: input_boolean.cat_alone
    state: "off"

variables:
  current_night_scene: !input night_scene

actions:
  - if:
      - condition: state
        entity_id: input_boolean.everyone_sleep
        state: "on"
    then:
      - if:
          - condition: template
            value_template: "{{ current_night_scene is not none  }}"
        then:
          - action: scene.turn_on
            target:
              entity_id: !input night_scene
          - wait_for_trigger:
              trigger: state
              entity_id: !input presence_sensor
              from: "on"
              to: "off"
          - sequence: !input extra_off
          - action: light.turn_off
            target: !input light
    else:
      - action: light.turn_on
        target: !input light
      - wait_for_trigger:
          trigger: state
          entity_id: !input presence_sensor
          from: "on"
          to: "off"
      - if:
          - condition: state
            entity_id: input_boolean.stop
            state: "off"
        then:
          - sequence: !input extra_off
          - action: light.turn_off
            target: !input light
